apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vprofile-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/sinchan62/vprofile-Argocd.git
    targetRevision: test-env
    path: mainfest
  destination: 
    server: https://kubernetes.default.svc
    namespace: myapp

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true