apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vprodb
  template:
    metadata:
      name: vprodb
      labels:
        app: vprodb
    spec:
      containers:
        - name: vprodb
          image: vprofile/vprofiledb:latest
          resources:
            limits:
              memory: "1Gi"
              cpu: "500m"
          ports:
            - name: db-ports
              containerPort: 3306
          volumeMounts:
            - name: data-volume
              mountPath: /var/lib/mysql 
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db-pass
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: db-pvc
